# Generated by Django 3.0.8 on 2020-08-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200811_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
    ]
